const Home = async function (res) {

  const { header, footer } = require('../components');

  const content = `<h1>Miranda Sorventi</h1>
Miranda Sorventi was born in 1985 in a small village in Italy, coincidentally only a few kilometers from where Leonardo da Vinci was born. From an early age it was clear that Miranda possessed exceptional intelligence, as well as deep artistic gifts. Miranda taught herself to read before she could speak, and was late to begin speaking at all. When she did begin speaking at the age of four she spoke in complete, lengthy sentences of grammatical perfection, tinged with humor and deliberate ambiguity. It was also at the age of four that she completed her first drawing, an astonishing, highly detailed sepia of a fruit fly, which she labeled "<i>drosophila</i> deliberately in the style of Leonardo."
<p>Miranda's parents, Arturo and Gabriella, were both artisans&mdash;he in pottery, and she in jewelery. Both were relatively uneducated, having barely graduated from high school, but Miranda grew up in an environment of creativity and fine esthetics.</p>
<p>There was a small library in the village, and beginning at the age of five Miranda would visit the library every day it was open, reading everything she could. There was a large dictionary of Italian in the library, which Miranda could frequently be seen studying with great intensity. Miranda's gifts of both memory and creative language soon began to become known. One day the librarian playfully challenged Miranda to define words from random pages of the dictionary, and was shocked to find that Miranda could remember every definition she had read, and was close to completing her reading of the entire dictionary.</p>
<p>Soon Miranda began making jokes based on her own creative variations of advanced vocabulary. She would laugh heartily at her own jokes, but her parents did not understand her jokes, which really could only be understood by Miranda and experts in semantics and etymology. This all began as Miranda turned six years old.</p>
<p>One year later Miranda's parents were in for a shock when she returned home one day speaking perfect, fluent English with no accent. "Come hai fatto?" ("How did you do this?") her father exclaimed. "I found some tapes in the library, some books and a dictionary, and studied hard for a couple of weeks." Miranda responded matter of factly. "It will take me another week or so to start telling my weird obscure language jokes in English." A week later, the obscure language jokes in English started, with Miranda laughing to herself because she was the only person who could understand them.</p>
<p>Word of Miranda's strange accomplishments began to spread, first in the village, then rapidly beyond. Soon Miranda was being referred to as "la ragazza miracolosa," "the miracle girl." She paid no attention to this, only continuing her treks to the library to study. Soon the villagers would pass her on the street and ask her "What are you studying now, Miranda?" The list of Miranda's answers was long. "Chemistry" she would respond, or "differential equations" or "social psychology" or just "art."</p>
<p>Then the art began, first in Miranda's tiny bedroom. She asked her father for a piece of clay, and a pen knife. A few hours later her father discovered a perfect tiny sculpture of a peasant boy with a goat, each detail perfectly carved, and in a uniquely expressive style. Arturo began sobbing, saying to himself through his tears "Io non sono un genio, ma mia figlia lo è." ("I am no genius, but my daughter is.") The tiny, perfect sculpture was then followed by a series of small paintings, each of them gloriously beautiful and unique. Arturo and Gabriella were at a loss. "La ragazza miracolosa" was their responsibility, and they just didn't know what to do. Meanwhile, Miranda's visits to the library continued, her mind growing stronger and deeper with each trip.</p>
<p>A retired professor lived in the village, so Arturo and Gabriella went to him for advice. He suggested that Miranda be given the Esame di Stato, or Maturità as it is commonly known in Italy, the exam that all students take after high school in order to qualify for university studies. Arturo asked Miranda whether she wanted to try this, and Miranda smiled and said "That sounds like fun!" So she took the exam, and got a perfect score at the age of eight. She was then given an IQ test, the results of which couldn't be evaluated because she got another perfect score. There was simply no way of measuring her IQ, because her mind was already so advanced at the age of barely eight.</p>
<p>Miranda's parents then began to wonder whether they had given birth to an alien. But if Miranda was an alien, she was an alien who looked just like them, and was also wonderfully friendly and down to earth, playing with other children in the normal way, and taking an earnest interest in nature. From her deep interest in nature drawing after drawing then emerged, in a style strangely similar to that of the great Leonardo, only a few kilometers away. Soon Miranda would be burdened with the appelation she would find distasteful for the rest of her life: "La moderna Leonardo donna," ("The modern female Leonardo.") or, to Miranda's further distaste, "Leonarda."</p>
<p>There is much more to Miranda's story, but we will leave it at this for now. Suffice it to say that Miranda Sorventi is the creator of Adventure Cabaret.</p>
<br><br><br><br>`;

  res.send(`${header('Adventure Cabaret')}
${content}
${footer}`);

}

module.exports = Home;